//You are given two strings s and t. 
//
// String t is generated by random shuffling string s and then add one more 
//letter at a random position. 
//
// Return the letter that was added to t. 
//
// 
// Example 1: 
//
// 
//Input: s = "abcd", t = "abcde"
//Output: "e"
//Explanation: 'e' is the letter that was added.
// 
//
// Example 2: 
//
// 
//Input: s = "", t = "y"
//Output: "y"
// 
//
// 
// Constraints: 
//
// 
// 0 <= s.length <= 1000 
// t.length == s.length + 1 
// s and t consist of lowercase English letters. 
// 
//
// Related TopicsHash Table | String | Bit Manipulation | Sorting 
//
// 👍 5404, 👎 510bug 反馈 | 使用指南 | 更多配套插件 
//
//
//
//


#include "../../../stdc.h"
using namespace std;

//leetcode submit region begin(Prohibit modification and deletion)
class Solution {
public:
    char findTheDifference(string s, string t) {
        // String t is generated by random shuffling string s and then add one more
        //letter at a random position.
        // s and t consist of lowercase English letters.
        if(s.empty()){return t[0];}
        std::vector<int> v(26,0);
        // 统计
        for(auto& ch:s){++v[ch-'a'];}
        // 比较
        for(auto& ch:t){--v[ch-'a'];}
        for(int i=0;i<26;++i){
            if(v[i]){return 'a'+i;}
        }
        return '\0';
    }
};
//leetcode submit region end(Prohibit modification and deletion)
